server:
  port: 8180
management:
  server:
    port: 8180
  metrics:
    export:
      simple:
        enabled: true
    web:
      base:
        path: "/actuator"
      server:
        auto-time-requests: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      apache:
        catalina: WARN
      springframework: WARN
    space.schellenberger.etl.shopware2lexware: DEBUG
    space.schellenberger.etl.shopware2lexware.services: WARN
    com:
      zaxxer:
        hikari: WARN
spring:
  datasource:
    url: "jdbc:h2:file:./job-status-datenbank"
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: "update"
  batch:
    job:
      enabled: false